### ISSUE TITLE
[USER] Zobrazovanie vysledkov aktualne prihlaseneho studenta

### ISSUE THREAD

**Issue by Chiff** [Chiff/webtech2019#1]
**Is your feature request related to a problem? Please describe.**
Po prihlásení sa študentovi zobrazia výsledky zo všetkých predmetov, v ktorých mu bolo zadané hodnotenie

**Describe the solution you'd like**
Select z db aktualne prihlaseneho studenta a nasledovne vypisanie tabulky na main page

**Comment by Chiff** [comment]
Rest API pripravena 75d71b121f1550392a7d650f56838e5e85ef6f6b

**Comment by Mr-SvaRoq** [comment]
@Chiff 
[commit](https://github.com/Chiff/webtech2019/commit/ff6ddfd4bcf8f111aaa357e2b1bc3d2d87ab9121)
Ten isty problem s DB ... Treba doriesit
