### ISSUE TITLE
[ADMIN] EvalTool statistika

### ISSUE THREAD

**Issue by Chiff** [Chiff/webtech2019#12]
**Is your feature request related to a problem? Please describe.**
Pri tejto úlohe zobrazte niekde na vhodnom mieste ešte štatistické údaje typu:
* počet študentov v predmete
* počet súhlasiacich študentov
* počet nesúhlasiacich študentov
* počet študentov, ktorí sa nevyjadrili

* počet tímov
* počet uzavretých tímov
* počet tímov, ku ktorým sa treba vyjadriť
* počet tímov s nevyjadrenými študentami

Tieto údaje zobrazte aj do dvoch koláčovitých grafov.

**Describe the solution you'd like**
Sidebar? pri projekte/predmete

**Comment by tbenco** [comment]
Statistika zatial pripravena ako podstranka 
get parameter pre statistiku predmetu
link:
../public/admin/eval-stats.php?project=15
