### ISSUE TITLE
[ADMIN] Posielanie mailov

### ISSUE THREAD

**Issue by DominikSimko** [Chiff/webtech2019#16]
**Rozposlanie mailov studentom**
- vyberiete šablónu z databázy na rozposlanie mailu,
- nalistujete súbor s údajmi o užívateľoch,
- zadefinujete, kto je odosielateľom danej emailovej správy (meno, email, login a v prípade potreby heslo pre SMTP server, meno a email môžu byť ako premenné tiež použité v šablóne mailu),
- zadefinujete názov správy,
- priložíte prílohu (pokiaľ sa administrátor rozhodne ju poslať).

**Comment by tbenco** [comment]
done
