### ISSUE TITLE
Jednotlivé stránky vytvoreného portálu musia byť responzívne a prispôsobené aj pre tlač !!

### ISSUE THREAD

**Issue by rhlatky** [Chiff/webtech2019#20]
Jednotlivé stránky vytvoreného portálu musia byť responzívne a prispôsobené aj pre tlač

**Comment by rhlatky** [comment]
@Mr-SvaRoq tabulky tlac

**Comment by Mr-SvaRoq** [comment]
ak len tabulky tlacit, je to hotove

**Comment by Mr-SvaRoq** [comment]
I guess its done
