### ISSUE TITLE
U2 - pohlad studenta - kapitan

### ISSUE THREAD

**Issue by rhlatky** [Chiff/webtech2019#21]
Po prihlásení sa „kapitána tímu“ sa mu zobrazia celkové body, ktoré boli pridelené tímu a zoznam všetkých
študentov v tíme (vrátane jeho samotného), pričom pri každom zo študentov bude zobrazené textové pole, do
ktorého bude môcť zapísať jeho body. Treba ošetriť, aby sa do textových polí dali zadávať iba celočíselné hodnoty
a zároveň treba zabezpečiť, aby sa skontrolovalo, že súčet rozdelených bodov je rovný počtu pridelených bodov.

**Comment by tbenco** [comment]
done
