### ISSUE TITLE
U2 - pohlad studenta - teammate

### ISSUE THREAD

**Issue by rhlatky** [Chiff/webtech2019#22]
Po prihlásení sa „nekapitána tímu“ sa každému členovi tímu zobrazí rozdelenie bodov medzi jednotlivými členmi
tímu a tlačidlá „Súhlasím“ a „Nesúhlasím“. Po kliknutí na jedno z nich sa vyžiada potvrdenie zvoleného odklepnutia
a stav odklepnutia sa zobrazí na obrazovke pri mene daného člena tímu. Tento stav je už potom nemenný.

**Comment by tbenco** [comment]
done
