### ISSUE TITLE
[ADMIN] Prehlad vsetkych vysledkov predmetu

### ISSUE THREAD

**Issue by Chiff** [Chiff/webtech2019#4]
**Is your feature request related to a problem? Please describe.**
* Administrátor si bude môcť naviac pozrieť pri danom predmete a školskom roku aj importované výsledky pre všetkých študentov, ktoré budú zobrazené v tabuľke. 
* Túto tabuľku si bude možné vytlačiť aj do pdf súboru.

**Comment by Chiff** [comment]
Rest API pripravena 61e12fd871bb4cd856bafe5b020508e4ffaa8c0e
 
API Link: `...public/api/results.php?subject=2`

**Comment by Mr-SvaRoq** [comment]
@Chiff 
[commit](https://github.com/Chiff/webtech2019/commit/ff6ddfd4bcf8f111aaa357e2b1bc3d2d87ab9121)
Ten problem s DB nie je vyrieseny
