### ISSUE TITLE
[USER] login

### ISSUE THREAD

**Issue by Chiff** [Chiff/webtech2019#7]
**Is your feature request related to a problem? Please describe.**
* Prihlasenie IBA existujuceho studenta 
* Protectnutie routes podla toho ci (nie) je prihlaseny student/admin
* LDAP/db login

**Comment by Mr-SvaRoq** [comment]
@Chiff
verify this [commit](https://github.com/Chiff/webtech2019/commit/ff6ddfd4bcf8f111aaa357e2b1bc3d2d87ab9121) please.
